name: Akamai Secure LKE Pipeline

on:
  push:
    branches: [ "*" ]
    paths-ignore:
      - ".gitignore"
      - "*.md"
      - "banner.txt"
      - "deploy.sh"
      - "/bin/*.sh"
      - "/etc/deployments.yaml"
      - "/etc/services.yaml"
      - "/iac/*.tf"
      - "LICENSE"

permissions:
  contents: read

jobs:
  build:
    name: Jobs
    runs-on: ubuntu-latest

    steps:
      - name: Download the project files.
        uses: actions/checkout@v3

      - name: Package services.
        run: ./package.sh

      - name: Publish services.
        env:
          DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
        run: ./publish.sh
